# Generated by Django 2.0.5 on 2018-05-27 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoShift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vacation_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoShift.Employees', to_field='uid')),
            ],
        ),
    ]
