# Generated by Django 2.0.5 on 2018-05-28 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AutoShift', '0002_vacation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workhours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('month', models.IntegerField()),
                ('workhours', models.FloatField(null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AutoShift.Employees', to_field='uid')),
            ],
        ),
        migrations.RenameModel(
            old_name='ScheRequired',
            new_name='Arrangement',
        ),
        migrations.RenameField(
            model_name='vacation',
            old_name='vacation_uid',
            new_name='employee',
        ),
        migrations.AddField(
            model_name='shifts',
            name='hours',
            field=models.FloatField(null=True),
        ),
    ]
