# Generated by Django 2.0.5 on 2018-05-28 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoShift', '0003_auto_20180528_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workhours',
            name='date',
        ),
    ]
